---
title: "Hexbins"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.dim = c(6, 5), 
                      dpi = 200, 
                      out.width = '100%')
```

```{r}
library("mxmaps")

data("df_mxstate_2020")
df_mxstate$value = df_mxstate$afromexican / df_mxstate$pop * 100
mxhexbin_choropleth(df_mxstate, num_colors = 1,
                    title = "Percentage of the population that identifies as Afro-Mexican",
                    legend = "%")

```

## Text Shadow

You can use ```label_color``` if you want the state abbreviations in a different color than the default black, and you can also add a ```shadow_color``` if you want to the state abbreviation labels to have a shadow to better distinguish them from the background colors.

```{r message=FALSE,warning=FALSE}
library("viridis")
library("scales")

df_mxstate_2020$value = df_mxstate_2020$afromexican / df_mxstate_2020$pop 
# Will show a warning, look at the municipio examples to see how to remove it
mxhexbin_choropleth(df_mxstate_2020, 
                    num_colors = 1,
                    label_color = "white",
                    shadow_color = "black",
                    title = "Percentage of the population that identifies as Afro-Mexican",
                    legend = "%",
                    label_size = 3.8) +
  scale_fill_viridis("percentage", labels = percent)

```
