---
title: "Leaflet Municipios"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      fig.dim = c(6, 6), 
                      dpi = 100, 
                      out.width = '100%')
```

```{r}
library(mxmaps)
library(leaflet) # for colorNumeric

df_mxmunicipio$value <- df_mxmunicipio$indigenous / df_mxmunicipio$pop
#Viridis color scheme
magma <- c("#000004FF", "#1D1146FF", "#50127CFF", "#822681FF", "#B63779FF", 
           "#E65163FF", "#FB8761FF", "#FEC387FF", "#FCFDBFFF")
pal <- colorNumeric(magma, domain = df_mxmunicipio$value)
mxmunicipio_leaflet(df_mxmunicipio,
                    pal,
                    ~ pal(value),
                    ~ sprintf("State: %s<br/>Municipio : %s<br/>Percent Indigenous: %s%%",
                              state_name, municipio_name, round(value * 100, 1))) %>%
  addLegend(position = "bottomright", 
            pal = pal, 
            values = df_mxmunicipio$value,
            title = "Percent<br>Indigenous",
            labFormat = labelFormat(suffix = "%",
                                    transform = function(x) {100 * x})) %>%
  addProviderTiles("CartoDB.Positron")
```

## City maps

You can also subset the data to only show certain municipios


```{r message=FALSE,warning=FALSE}
library("dplyr")
library("geojsonio")
library("jsonlite")

# Convert the topoJSON to spatial object
tmpdir <- tempdir()
# have to use RJSONIO or else the topojson isn't valid
write(RJSONIO::toJSON(mxmunicipio.topoJSON), file.path(tmpdir, "mun.topojson"))
muns <- topojson_read(file.path(tmpdir, "mun.topojson"))

# municipios that make up Monterrey
monterrey <- muns[muns$id %in% df_mxmunicipio$region[df_mxmunicipio$metro_area == "Monterrey"],]
# made-up data
monterrey@data$rand <- 1:nrow(monterrey@data)

# Create a continuous palette function
pal <- colorNumeric(
  palette = "Blues",
  domain = monterrey@data$rand
)

leaflet(monterrey) %>%
  addPolygons(stroke = FALSE, smoothFactor = 0.2, fillOpacity = 1,
              color = ~pal(monterrey@data$rand)
  )%>%
  addProviderTiles("CartoDB.Positron")
```
